Make the code look beautiful Part III
vtex/ab-tester pull request #57
Opened 2020-09-18 12:11 UTC by valentino-amadeus

#### What is the purpose of this pull request?
Reallocate `TestType` from `node/clients/vbase.ts` to `node/typings.d.ts`. 

#### What problem is this solving?
`TestType` is a crucial concept throughout the app, so that it makes more sense to keep it in `typings.d.ts`.

#### How should this be manually tested?
No test needed. Once it passes the builder check, it shall work fine. 

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2021-02-24 15:15 UTC, tergol1 requested changes

2021-02-24 15:15 UTC, tergol1 commented on node/clients/vbase.ts
> -
I think that remove this enum is what is bothering me about this change. Could you explain a bit your intention here?

2021-02-24 15:26 UTC, valentino-amadeus commented on node/clients/vbase.ts
> -
Removing the enum is all the PR does 😅 (together with adding it as a type to `typings.d.ts`, of course).
It's an improvement on the code's logic. The test type is a crucial concept throughout the code, so it doesn't make sense to define it in such a singular file and to import it everywhere else. `typings.d.ts` is the perfect place to insert foundational concepts.

2021-02-24 18:40 UTC, tergol1 commented on node/clients/vbase.ts
> -
Isn't it possible to make the global `TestType` a enum? I don't like to have always to write the exact sequence of characters everywhere.

2021-02-24 19:09 UTC, valentino-amadeus commented on node/clients/vbase.ts
> -
I'm with you on that, but unfortunately you can't define enums in `typings.d.ts`, as they are constants - not types.

2021-02-24 19:32 UTC, valentino-amadeus commented on node/clients/vbase.ts
> -
And even though we don't like the idea of writing the whole words every time, it does have an up side: we're not gonna confuse the types. When dealing with enums, we only specify the index, so that may bring confusion - or at least the obligation of checking what type has each index, which already consumes the time we'd spend writing the words 😅 .

2021-02-26 14:03 UTC, tergol1 approved these changes

2021-02-26 16:36 UTC, merged