Check workspace name before initializing and finishing
vtex/ab-tester pull request #76
Opened 2020-09-29 17:45 UTC by valentino-amadeus

#### What is the purpose of this pull request?
- Avoid initializing a test with a non-existing workspace, with a development workspace or with the `master` workspace. 
- Throw an error when trying to remove (`finish`) from the test the master workspace or a workspace that was not under test.

#### What problem is this solving?
- When initializing a test with a non-existing or with the master workspace, problems would appear at the Router.
- When removing from the test a workspace that was not being tested (that could occur because of a misspelling, for example), the set of workspaces under test would remain the same, but the proportions would be reset. 

#### How should this be manually tested?
- Call the initializing routes setting as workspace: 
    1. a name that does not correspond to any of the account's workspaces;
    2. a development workspace;
    3.  the `master` workspace;
    4. a production workspace
and verify whether the app responds as expected*.
- Call the finishing route setting as workspace:
    1. a name that does not correspond to any of the account's workspaces;
    2. one of the account's workspaces that are not under test;
    3. the `master` workspace;
    4. one of the workspaces under test
and verify whether the app responds as expected*.

\* <sub>You should also call the test's `status` to check if everything went as intended.</sub> 

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-09-29 18:55 UTC, tergol1 requested changes
We're almost there! I just proposed something to avoid some code repetition, but you can implement it the way you prefer. Then, I'll take a look again.

2020-09-29 18:55 UTC, tergol1 commented on node/abTest/commands/initialize.ts
> +        throw new Error(`Bad workspace name: please select another workspace`)
I think you should add the information about why this was not allowed.

2020-09-29 18:55 UTC, tergol1 commented on node/abTest/commands/initialize.ts
> +    await CheckWorkspace(workspaceName, ctx)
Looking this repetition that you introduced in this code I realized that we were already repeating a lot of things here. WDYT of creating a helper `initializeAbTestForWorkspace ` that has as parameters everything that could be used to initialize a test, i.e. workspace names, parameters, etc, and then we use only small functions - the ones that we have today, but simpler - to only parse these parameters and then call this helper with what is necessary?

2020-09-29 19:51 UTC, valentino-amadeus commented on node/abTest/commands/initialize.ts
> +        throw new Error(`Bad workspace name: please select another workspace`)
Right! I thought the message would become too large, but since you find that that would be better too, I'll do it!

2020-09-29 19:52 UTC, valentino-amadeus commented on node/abTest/commands/initialize.ts
> +    await CheckWorkspace(workspaceName, ctx)
That seems awesome! This repetition has been bothering me for a while haha.

2020-12-01 03:24 UTC, tergol1 approved these changes
LGTM

2020-12-01 03:24 UTC, tergol1 commented on node/abTest/commands/initialize.ts
> +    if (Type !== 'conversion' && Type !== 'revenue') {
WDYT about creating constants for these strings? We'll probably use it more times in the code.

2020-12-02 01:53 UTC, valentino-amadeus commented on node/abTest/commands/initialize.ts
> +    if (Type !== 'conversion' && Type !== 'revenue') {
They were constants before, but I changed it. https://github.com/vtex/ab-tester/pull/57
It bothers me that they are not constants, but it bothers me even more if they are defined in a file other than `typings.d.ts`. Do you see any drawbacks in the way these types are currently defined?

2021-03-23 13:57 UTC, merged